### ISSUE TITLE
Crash when sending empty body on channels/<id> 

### ISSUE THREAD

**Issue by leplatrem** [webpush-channels/webpush-channels#19]

**Comment by mansimarkaur** [comment]
WebPush is does not handle empty payload.
the `send` method calls the `encode` method which in turn calls the `http_ece.encrypt` method.
The encrypt method tries to use the length of the payload but crashes because the payload is `None`.

**Comment by mansimarkaur** [comment]
Here's the error if I try to ring the bell using the demo pushbell:
```
2017-02-17 22:44:03,166 ERROR [kinto.core.views.errors:112][waitress] "POST  /v0/channels/bell" ? (? ms) object of type 'NoneType' has no len() agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:51.0) Gecko/20100101 Firefox/51.0 authn_type=basicauth errno=None exception=Traceback (most recent call last):
  File "/Users/mkaur/Sites/webpush-channels/.venv/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/Users/mkaur/Sites/webpush-channels/.venv/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 119, in tm_tween
    reraise(*exc_info)
  File "/Users/mkaur/Sites/webpush-channels/.venv/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 98, in tm_tween
    response = handler(request)
  File "/Users/mkaur/Sites/webpush-channels/.venv/lib/python2.7/site-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/Users/mkaur/Sites/webpush-channels/.venv/lib/python2.7/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/Users/mkaur/Sites/webpush-channels/.venv/lib/python2.7/site-packages/pyramid/config/views.py", line 182, in __call__
    return view(context, request)
  File "/Users/mkaur/Sites/webpush-channels/.venv/lib/python2.7/site-packages/pyramid/viewderivers.py", line 393, in attr_view
    return view(context, request)
  File "/Users/mkaur/Sites/webpush-channels/.venv/lib/python2.7/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
    return view(context, request)
  File "/Users/mkaur/Sites/webpush-channels/.venv/lib/python2.7/site-packages/pyramid/viewderivers.py", line 302, in _secured_view
    return view(context, request)
  File "/Users/mkaur/Sites/webpush-channels/.venv/lib/python2.7/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
    result = view(context, request)
  File "/Users/mkaur/Sites/webpush-channels/.venv/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/Users/mkaur/Sites/webpush-channels/.venv/lib/python2.7/site-packages/cornice/service.py", line 493, in wrapper
    response = view_(request)
  File "/Users/mkaur/Sites/webpush-channels/webpush_channels/views/channels.py", line 57, in send_push_notifications
    push_initialize.send(data=data, ttl=15)
  File "/Users/mkaur/Sites/webpush-channels/.venv/lib/python2.7/site-packages/pywebpush/__init__.py", line 172, in send
    encoded = self.encode(data)
  File "/Users/mkaur/Sites/webpush-channels/.venv/lib/python2.7/site-packages/pywebpush/__init__.py", line 146, in encode
    authSecret=self.auth_key)
  File "/Users/mkaur/Sites/webpush-channels/.venv/lib/python2.7/site-packages/http_ece/__init__.py", line 150, in encrypt
    for i in list(range(0, len(buffer) + padSize, rs)):
TypeError: object of type 'NoneType' has no len() lang=en-US,en;q=0.5 uid=eb05d2f05022fb52965eca22a1258e80e5e62015fc3a37769d597c02d8d41d7c
```

**Comment by Natim** [comment]
It does with pywebpush 0.7.0 that [was released today](https://pypi.python.org/pypi/pywebpush).

**Comment by Natim** [comment]
Can you tell me if running: `.venv/bin/pip install -U pywebpush` fixes it?

**Comment by mansimarkaur** [comment]
Yes, it's working now.
